var a= prompt("Enter the integer number");
document.write("The value of a is "+a);
document.write("<br>"+"<br>"+"The value of ++a is "+ ++a);
document.write("<br>"+"Now the value of a is "+ a);
document.write("<br>"+"<br>"+"The value of a++ is "+ a++);
document.write("<br>"+"Now the value of a is "+ a);
document.write("<br>"+"<br>"+"The value of --a is "+ --a);
document.write("<br>"+"Now the value of a is "+ a);
document.write("<br>"+"<br>"+"The value of a-- is "+ a--);
document.write("<br>"+"Now the value of a is "+ a);